### PR TITLE
Feat: fix flashing issue when updating code and enable code edit

### PR DESCRIPTION
**Pull request by clean99**
1. Update the way of updating code in `iframe`, so that the iframe won't reload every time the code is changed to prevent flashing.
Instead of using the srcDoc property, consider using JavaScript to update the content of the iframe. This can be done by accessing the iframe's document object and directly writing the new HTML content to it. This approach avoids reloading the iframe, thus preventing the refresh issue.

2. Enable code edit feature.
Add listener to detect code changes and update local state

#55

### CODE REVIEW

**Comment by abi** [comment]
Nice job! Will test this in the morning and merge.

Can you test if follow-up changes after the first generation still work correctly when we update generatedCode? The follow-up changes get the entire history of the app (prompt and completion) up to that point.

**Comment by clean99** [comment]
> Nice job! Will test this in the morning and merge.
> 
> Can you test if follow-up changes after the first generation still work correctly when we update generatedCode? The follow-up changes get the entire history of the app (prompt and completion) up to that point.

Let me test this first

**Comment by clean99** [comment]
@abi  tested, fix a bug now should be all good.

**Review by K370sis — CHANGES_REQUESTED** [review]
[deleted]

**Comment by abi** [comment]
the lack of flashing is really nice!

**Pull request merged**
