### PR TITLE
Feat/add ionic support and check select option

### PR DESCRIPTION
**Pull request by dialmedu**
I add check logic when update option of output settings, if is hidden options then disabled this options and change to default values, and show final output settings.

support_ionic_change_settings
this flow use:

image

For ionic support use  this links and scripts.
```
     
    <script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.esm.js"></script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core/dist/ionic/ionic.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core/css/ionic.bundle.css" />
 
```
- For icons use ionicons:

```
    <script type="module">
        import ionicons from 'https://cdn.jsdelivr.net/npm/ionicons/+esm'
    </script>
    <script nomodule src="https://cdn.jsdelivr.net/npm/ionicons/dist/esm/ionicons.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/ionicons/dist/collection/components/icon/icon.min.css" rel="stylesheet">

```

### CODE REVIEW

**Comment by abi** [comment]
Nice job! Will merge ionic support today.

The problem I have with disabling an option completely is that then it's not obvious to the user how to enable it. That's why I prefer having all options enabled, when the user chooses "Ionic", we just reset their framework choice to the compatible ones and display a message. Need to think more on this UI.

**Comment by abi** [comment]
Didn't have enough time to merge ionic today but will do tomm

**Comment by abi** [comment]
Simplifed the UI a lot. Code is also way cleaner this way.

Screenshot 2023-11-30 at 4 10 06 PM

When we get too many supported code options, we can rethink about the dropdown.

Thanks for this PR!

**Comment by dialmedu** [comment]
I will be working on supporting flutter and evaluating svelte.

**Pull request merged**
