### PR TITLE
Feat: support generate react code

### PR DESCRIPTION
**Pull request by clean99**
#96 

## Background

Now our system only supports generating HTML. However, the frontend community now mainly uses React, and Vue as development frameworks/libraries. Thus adding react generation capacity is crucial.

## Methods

There are two ways to generate react code:

1. **image → react**: Feed GPT the same materials as we generate HTML, and prompt GPT to generate React(and other) code.
2. **image → html → react**: Prompt GPT to translate HTML into React code.

Here are some simple investigations of the advantages of these two methods:

  | image → react | image → html → react
-- | -- | --
Accuracy | ✅ |  
Performance | ✅ |  
Token Cost | ✅ |  
Modularity | ✅ |  
Community | ✅ |  
Complexity |   | ✅

## Accuracy

There are certain accuracy losses when we use GPT to translate something, no matter if it is from image to code, or code to code. From this perspective, directly generating react code is expected to perform better than image → html → react.

### Performance/Token Cost

image → html → react requires at least 2 rounds of GPT query, while image → react requires at least 1 round of GPT query. So image → react outperforms image → html → react.

### Modularity

HTML makes it hard to abstract components. Image → react opens a door to **generate components** in the future, which is a good way to handle complexity especially when GPT’s capacity is not good enough for now.

### Community

Image → react allows GPT to utilize the npm libraries. Image → html → react hinders GPT from using the library when it is generating HTML, and the translation from HTML to react will follow the thought expressed in HTML.

### Complexity

image → html → react is way easier than generating image → react from a development effort perspective.

## System Design

For now, we still emphasize the HTML generation given that there isn’t a way to display the render result of react code directly(Plan to add in future leveraging code sandbox). So HTML should be always generated in every update. React code will be an extra button next to the tabs. In the future, if we plan to support other frameworks like Vue, we can add a selection for users.

1. Home Page

generate react code home

We will make this tab lazy loaded by default, given that now it is not the main feature of our system, always generating two pieces of code makes a significant cost. 

2. React Code Dialog

We will separate the flow of react generation from HTML generation, which means that they will have different instructions and update history. Because two pieces of code should have different instructions.

A dialog is thus created for the user to preview React’s code and provide instructions for updating the code. (In the future, when we have the capacity to preview react code render result), we may remove this and reuse the home page of HTML totally.

The basic flow is: user open react generation dialog -> auto execute generate react code -> user modify code and input instructions -> click on update -> regenerate code.

generate react code dialog

3. Interface
- Reuse /generate-code with a new param: `codeType`, when `codeType` is `react` use the `react` prompt.
- New prompt template: `REACT_GENERATION_SYSTEM_PROMPT`

### CODE REVIEW

**Comment by clean99** [comment]
> Output settings

Thanks for sharing this! I will take a look at how to implement it.

The question I have about the output setting is now the system record history, and if we wanna reuse the same logic for different language, the history would be messive for GPT to understand, We may need a more sophisticated history protocol.

My suggestion is to separate the html and different languages out and provide a selection section for users when they enter the system, so that the user can select react, vue, or html one time, this makes the system much simpler compared to enabling users to switch between different languages after generating the code. What do you think? @abi

**Comment by abi** [comment]
@clean99 yeah, I don't think the user should be allowed to switch frameworks after the 1st generation. They'll reset to change frameworks. Don't think there's a real use case where you want to switch frameworks in the middle.

**Comment by clean99** [comment]
> @clean99 yeah, I don't think the user should be allowed to switch frameworks after the 1st generation. They'll reset to change frameworks. Don't think there's a real use case where you want to switch frameworks in the middle.

Great, I will design and update later

**Comment by abi** [comment]
I'm working on a version that I'll push today as well.

**Comment by abi** [comment]
I pushed React generation to master today. Check it out, and let me know if there's some improvements we can make.

**Comment by abi** [comment]
This functionality is now in master so closing this PR. Thanks for investigating and creating this PR.

**Pull request closed without merging**
